[package]
name = "aoc8"
version = "0.1.0"
authors = ["Drew Vogel <dvogel@github>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
regex = "1.4.2"
